-- begin TECHNIKA_DEVICE_TYPE
create unique index IDX_TECHNIKA_DEVICE_TYPE_UNIQ_NAME on TECHNIKA_DEVICE_TYPE (NAME) ^
-- end TECHNIKA_DEVICE_TYPE
-- begin TECHNIKA_DEVICE
alter table TECHNIKA_DEVICE add constraint FK_TECHNIKA_DEVICE_ON_TYPE foreign key (TYPE_ID) references TECHNIKA_DEVICE_TYPE(ID)^
alter table TECHNIKA_DEVICE add constraint FK_TECHNIKA_DEVICE_ON_VENDOR foreign key (VENDOR_ID) references TECHNIKA_VENDOR(ID)^
create unique index IDX_TECHNIKA_DEVICE_UNIQ_MODEL on TECHNIKA_DEVICE (MODEL) ^
create index IDX_TECHNIKA_DEVICE_ON_TYPE on TECHNIKA_DEVICE (TYPE_ID)^
create index IDX_TECHNIKA_DEVICE_ON_VENDOR on TECHNIKA_DEVICE (VENDOR_ID)^
-- end TECHNIKA_DEVICE
-- begin TECHNIKA_VENDOR
create unique index IDX_TECHNIKA_VENDOR_UNIQ_NAME on TECHNIKA_VENDOR (NAME) ^
-- end TECHNIKA_VENDOR
-- begin TECHNIKA_COMPONENT
alter table TECHNIKA_COMPONENT add constraint FK_TECHNIKA_COMPONENT_ON_DEVICE foreign key (DEVICE_ID) references TECHNIKA_DEVICE(ID)^
create index IDX_TECHNIKA_COMPONENT_ON_DEVICE on TECHNIKA_COMPONENT (DEVICE_ID)^
-- end TECHNIKA_COMPONENT
-- begin TECHNIKA_OFFICE
create unique index IDX_TECHNIKA_OFFICE_UNIQ_NAME on TECHNIKA_OFFICE (NAME) ^
-- end TECHNIKA_OFFICE
-- begin TECHNIKA_POST
create unique index IDX_TECHNIKA_POST_UNIQ_NAME on TECHNIKA_POST (NAME) ^
-- end TECHNIKA_POST
-- begin TECHNIKA_CONTRAGENT
create unique index IDX_TECHNIKA_CONTRAGENT_UNIQ_NAME on TECHNIKA_CONTRAGENT (NAME) ^
-- end TECHNIKA_CONTRAGENT
-- begin TECHNIKA_COST
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_CONTRAGENT foreign key (CONTRAGENT_ID) references TECHNIKA_CONTRAGENT(ID)^
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_MAIN_DOC foreign key (MAIN_DOC_ID) references SYS_FILE(ID)^
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_UPD foreign key (UPD_ID) references SYS_FILE(ID)^
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_PAYER foreign key (PAYER_ID) references TECHNIKA_PAYER(ID)^
create index IDX_TECHNIKA_COST_ON_CONTRAGENT on TECHNIKA_COST (CONTRAGENT_ID)^
create index IDX_TECHNIKA_COST_ON_MAIN_DOC on TECHNIKA_COST (MAIN_DOC_ID)^
create index IDX_TECHNIKA_COST_ON_UPD on TECHNIKA_COST (UPD_ID)^
create index IDX_TECHNIKA_COST_ON_PAYER on TECHNIKA_COST (PAYER_ID)^
-- end TECHNIKA_COST
-- begin TECHNIKA_PAYER
create unique index IDX_TECHNIKA_PAYER_UNIQ_NAME on TECHNIKA_PAYER (NAME) ^
-- end TECHNIKA_PAYER
-- begin TECHNIKA_EQUIPMENT
alter table TECHNIKA_EQUIPMENT add constraint FK_TECHNIKA_EQUIPMENT_ON_TECHNIKA foreign key (TECHNIKA_ID) references TECHNIKA_TECHIKA(ID)^
alter table TECHNIKA_EQUIPMENT add constraint FK_TECHNIKA_EQUIPMENT_ON_COMPONENT foreign key (COMPONENT_ID) references TECHNIKA_COMPONENT(ID)^
create index IDX_TECHNIKA_EQUIPMENT_ON_TECHNIKA on TECHNIKA_EQUIPMENT (TECHNIKA_ID)^
create index IDX_TECHNIKA_EQUIPMENT_ON_COMPONENT on TECHNIKA_EQUIPMENT (COMPONENT_ID)^
-- end TECHNIKA_EQUIPMENT
-- begin TECHNIKA_PERSON
alter table TECHNIKA_PERSON add constraint FK_TECHNIKA_PERSON_ON_OFFICE foreign key (OFFICE_ID) references TECHNIKA_OFFICE(ID)^
alter table TECHNIKA_PERSON add constraint FK_TECHNIKA_PERSON_ON_POST foreign key (POST_ID) references TECHNIKA_POST(ID)^
create unique index IDX_TECHNIKA_PERSON_UNIQ_EMAIL on TECHNIKA_PERSON (EMAIL) ^
create index IDX_TECHNIKA_PERSON_ON_OFFICE on TECHNIKA_PERSON (OFFICE_ID)^
create index IDX_TECHNIKA_PERSON_ON_POST on TECHNIKA_PERSON (POST_ID)^
-- end TECHNIKA_PERSON
