-- begin TECHNIKA_DEVICE_TYPE
create unique index IDX_TECHNIKA_DEVICE_TYPE_UNIQ_NAME on TECHNIKA_DEVICE_TYPE (NAME) ^
-- end TECHNIKA_DEVICE_TYPE
-- begin TECHNIKA_DEVICE
alter table TECHNIKA_DEVICE add constraint FK_TECHNIKA_DEVICE_ON_TYPE foreign key (TYPE_ID) references TECHNIKA_DEVICE_TYPE(ID)^
alter table TECHNIKA_DEVICE add constraint FK_TECHNIKA_DEVICE_ON_VENDOR foreign key (VENDOR_ID) references TECHNIKA_VENDOR(ID)^
create unique index IDX_TECHNIKA_DEVICE_UNIQ_MODEL on TECHNIKA_DEVICE (MODEL) ^
create index IDX_TECHNIKA_DEVICE_ON_TYPE on TECHNIKA_DEVICE (TYPE_ID)^
create index IDX_TECHNIKA_DEVICE_ON_VENDOR on TECHNIKA_DEVICE (VENDOR_ID)^
-- end TECHNIKA_DEVICE
-- begin TECHNIKA_VENDOR
create unique index IDX_TECHNIKA_VENDOR_UNIQ_NAME on TECHNIKA_VENDOR (NAME) ^
-- end TECHNIKA_VENDOR
-- begin TECHNIKA_COMPONENT
alter table TECHNIKA_COMPONENT add constraint FK_TECHNIKA_COMPONENT_ON_DEVICE foreign key (DEVICE_ID) references TECHNIKA_DEVICE(ID)^
create index IDX_TECHNIKA_COMPONENT_ON_DEVICE on TECHNIKA_COMPONENT (DEVICE_ID)^
-- end TECHNIKA_COMPONENT
