alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_CONTRAGENT foreign key (CONTRAGENT_ID) references TECHNIKA_CONTRAGENT(ID);
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_MAIN_DOC foreign key (MAIN_DOC_ID) references SYS_FILE(ID);
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_UPD foreign key (UPD_ID) references SYS_FILE(ID);
alter table TECHNIKA_COST add constraint FK_TECHNIKA_COST_ON_PAYER foreign key (PAYER_ID) references TECHNIKA_PAYER(ID);
create index IDX_TECHNIKA_COST_ON_CONTRAGENT on TECHNIKA_COST (CONTRAGENT_ID);
create index IDX_TECHNIKA_COST_ON_MAIN_DOC on TECHNIKA_COST (MAIN_DOC_ID);
create index IDX_TECHNIKA_COST_ON_UPD on TECHNIKA_COST (UPD_ID);
create index IDX_TECHNIKA_COST_ON_PAYER on TECHNIKA_COST (PAYER_ID);
