alter table TECHNIKA_MOVEMENT add constraint FK_TECHNIKA_MOVEMENT_ON_PERSON foreign key (PERSON_ID) references TECHNIKA_PERSON(ID);
alter table TECHNIKA_MOVEMENT add constraint FK_TECHNIKA_MOVEMENT_ON_TECHNIKA foreign key (TECHNIKA_ID) references TECHNIKA_TECHIKA(ID);
create index IDX_TECHNIKA_MOVEMENT_ON_PERSON on TECHNIKA_MOVEMENT (PERSON_ID);
create index IDX_TECHNIKA_MOVEMENT_ON_TECHNIKA on TECHNIKA_MOVEMENT (TECHNIKA_ID);
