alter table TECHNIKA_EQUIPMENT add constraint FK_TECHNIKA_EQUIPMENT_ON_TECHNIKA foreign key (TECHNIKA_ID) references TECHNIKA_TECHIKA(ID);
alter table TECHNIKA_EQUIPMENT add constraint FK_TECHNIKA_EQUIPMENT_ON_COMPONENT foreign key (COMPONENT_ID) references TECHNIKA_COMPONENT(ID);
create index IDX_TECHNIKA_EQUIPMENT_ON_TECHNIKA on TECHNIKA_EQUIPMENT (TECHNIKA_ID);
create index IDX_TECHNIKA_EQUIPMENT_ON_COMPONENT on TECHNIKA_EQUIPMENT (COMPONENT_ID);
