alter table TECHNIKA_COMPONENT add constraint FK_TECHNIKA_COMPONENT_ON_COST foreign key (COST_ID) references TECHNIKA_COST(ID);
create index IDX_TECHNIKA_COMPONENT_ON_COST on TECHNIKA_COMPONENT (COST_ID);
