alter table TECHNIKA_PERSON add constraint FK_TECHNIKA_PERSON_ON_OFFICE foreign key (OFFICE_ID) references TECHNIKA_OFFICE(ID);
alter table TECHNIKA_PERSON add constraint FK_TECHNIKA_PERSON_ON_POST foreign key (POST_ID) references TECHNIKA_POST(ID);
create unique index IDX_TECHNIKA_PERSON_UNIQ_EMAIL on TECHNIKA_PERSON (EMAIL) ;
create index IDX_TECHNIKA_PERSON_ON_OFFICE on TECHNIKA_PERSON (OFFICE_ID);
create index IDX_TECHNIKA_PERSON_ON_POST on TECHNIKA_PERSON (POST_ID);
